[project]
name = 'contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.h_n_t]
path = 'contracts/h_n_t.clar'
clarity_version = 2
epoch = 2.4

[contracts.hello-stacks]
path = 'contracts/hello-stacks.clar'
clarity_version = 2
epoch = 2.4

[contracts.test-contract]
path = 'contracts/test-contract.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
